### ISSUE TITLE
build failed for map elites

### ISSUE THREAD

**Issue by ashiqimran** [sferes2/map_elites#1]
I am a neophyte using sferes2. I successfully built basic speres2 framework. I need to build map_elites module. When I try to build it, it shows 

Build failed:
 -> task failed (err #1): 
    {task: cxx test_map_elites.cpp -> test_map_elites_1.o}
 -> task failed (err #1): 
    {task: cxx test_map_elites.cpp -> test_map_elites_1.o}

Please help

**Comment by jbmouret** [comment]
Hi

Can you copy/paste the full compilation log including your commands)?

Thanks

**Comment by ashiqimran** [comment]
Here, I pasted the compilation log. I just use ./waf build in sferes2 directory.

module : [modules/nn2]
module : [modules/map_elites]
Waf: Entering directory `/home/ashiq/Desktop/sferes2/build'
Entering directory`/home/ashiq/Desktop/sferes2'
Entering directory `/home/ashiq/Desktop/sferes2/modules/'
Entering directory`/home/ashiq/Desktop/sferes2/modules/'
[ 27/106] cxx: modules/map_elites/test_map_elites.cpp -> build/default/modules/map_elites/test_map_elites_1.o
[ 54/106] cxx: modules/map_elites/test_map_elites.cpp -> build/debug/modules/map_elites/test_map_elites_1.o
../modules/map_elites/test_map_elites.cpp:84:5: warning: "/_" within comment [-Wcomment]
     /_SFERES_CONST size_t res_x = 256;
 ^
../modules/map_elites/test_map_elites.cpp:84:5: warning: "/_" within comment [-Wcomment]
     /_SFERES_CONST size_t res_x = 256;
 ^
../modules/map_elites/test_map_elites.cpp:90:3: error: expected declaration before ‘}’ token
   };
   ^
In file included from /usr/include/boost/assert.hpp:50:0,
                 from /usr/include/boost/filesystem/operations.hpp:36,
                 from /usr/include/boost/filesystem.hpp:17,
                 from ../sferes/ea/ea.hpp:58,
                 from ../modules/map_elites/map_elites.hpp:49,
                 from ../modules/map_elites/test_map_elites.cpp:56:
../modules/map_elites/test_map_elites.cpp: In function ‘const size_t behav_shape(size_t)’:
../sferes/stc.hpp:126:25: error: ‘behav_shape_size’ was not declared in this scope
   { assert(i < A##_size()); SFERES_CONST T _##A[] = { __VA_ARGS__ }; return _##A[i]; } \
                         ^
../modules/map_elites/test_map_elites.cpp:88:5: note: in expansion of macro ‘SFERES_ARRAY’
     SFERES_ARRAY(size_t, behav_shape, 256, 256);
     ^
../modules/map_elites/test_map_elites.cpp: At global scope:
../modules/map_elites/test_map_elites.cpp:90:3: error: expected declaration before ‘}’ token
   };
   ^
Waf: Leaving directory `/home/ashiq/Desktop/sferes2/build'
Build failed:
 -> task failed (err #1): 
    {task: cxx test_map_elites.cpp -> test_map_elites_1.o}
 -> task failed (err #1): 
    {task: cxx test_map_elites.cpp -> test_map_elites_1.o}

**Comment by jbmouret** [comment]
Hi

It seems a star is missing line 84 after the �/�. It does not appear to be in the repo. Maybe you accidentally deleted it?

regards,
� JBM

On 03 Oct 2015, at 15:13, ashiqimran notifications@github.com wrote:

> Here, I pasted the compilation log. I just use ./waf build in sferes2 directory.
> 
> module : [modules/nn2]
> module : [modules/map_elites]
> Waf: Entering directory /home/ashiq/Desktop/sferes2/build'
> Entering directory/home/ashiq/Desktop/sferes2'
> Entering directory /home/ashiq/Desktop/sferes2/modules/'
> Entering directory/home/ashiq/Desktop/sferes2/modules/'
> [ 27/106] cxx: modules/map_elites/test_map_elites.cpp -> build/default/modules/map_elites/test_map_elites_1.o
> [ 54/106] cxx: modules/map_elites/test_map_elites.cpp -> build/debug/modules/map_elites/test_map_elites_1.o
> ../modules/map_elites/test_map_elites.cpp:84:5: warning: "/" within comment [-Wcomment]
> /SFERES_CONST size_t res_x = 256;
> ^
> ../modules/map_elites/test_map_elites.cpp:84:5: warning: "/" within comment [-Wcomment]
> /SFERES_CONST size_t res_x = 256;
> ^
> ../modules/map_elites/test_map_elites.cpp:90:3: error: expected declaration before �}� token
> };
> ^
> In file included from /usr/include/boost/assert.hpp:50:0,
> from /usr/include/boost/filesystem/operations.hpp:36,
> from /usr/include/boost/filesystem.hpp:17,
> from ../sferes/ea/ea.hpp:58,
> from ../modules/map_elites/map_elites.hpp:49,
> from ../modules/map_elites/test_map_elites.cpp:56:
> ../modules/map_elites/test_map_elites.cpp: In function �const size_t behav_shape(size_t)�:
> ../sferes/stc.hpp:126:25: error: �behav_shape_size� was not declared in this scope
> { assert(i < A##size()); SFERES_CONST T ##A[] = { __VA_ARGS }; return _##A[i]; } \
> ^
> ../modules/map_elites/test_map_elites.cpp:88:5: note: in expansion of macro �SFERES_ARRAY�
> SFERES_ARRAY(size_t, behav_shape, 256, 256);
> ^
> ../modules/map_elites/test_map_elites.cpp: At global scope:
> ../modules/map_elites/test_map_elites.cpp:90:3: error: expected declaration before �}� token
> };
> ^
> Waf: Leaving directory `/home/ashiq/Desktop/sferes2/build'
> Build failed:
> -> task failed (err #1): 
> {task: cxx test_map_elites.cpp -> test_map_elites_1.o}
> -> task failed (err #1): 
> {task: cxx test_map_elites.cpp -> test_map_elites_1.o}
> 
> �
> Reply to this email directly or view it on GitHub.

� Jean-Baptiste Mouret
http://pages.isir.upmc.fr/~mouret/

**Comment by ashiqimran** [comment]
Hi, I got into other problems. Please help.

module : [modules/nn2]
module : [modules/map_elites]
Waf: Entering directory `/home/ashiq/Desktop/sferes2/build'
Entering directory`/home/ashiq/Desktop/sferes2'
Entering directory `/home/ashiq/Desktop/sferes2/modules/'
Entering directory`/home/ashiq/Desktop/sferes2/modules/'
[ 27/106] cxx: modules/map_elites/test_map_elites.cpp -> build/default/modules/map_elites/test_map_elites_1.o
[ 54/106] cxx: modules/map_elites/test_map_elites.cpp -> build/debug/modules/map_elites/test_map_elites_1.o
../modules/map_elites/test_map_elites.cpp: In instantiation of ‘void Rastrigin<Params, Exact>::eval(Indiv&) [with Indiv = sferes::phen::Parameters<sferes::gen::EvoFloat<10, Params>, Rastrigin<Params>, Params>; Params = Params; Exact = stc::Itself]’:
../sferes/eval/parallel.hpp:63:11:   required from ‘void sferes::eval::_parallel_evaluate<Phen>::operator()(const range_t&) const [with Phen = sferes::phen::Parameters<sferes::gen::EvoFloat<10, Params>, Rastrigin<Params>, Params>; sferes::parallel::range_t = tbb::blocked_range<long unsigned int>]’
/usr/include/tbb/parallel_for.h:110:37:   required from ‘void tbb::interface6::internal::start_for<Range, Body, Partitioner>::run_body(Range&) [with Range = tbb::blocked_range<long unsigned int>; Body = sferes::eval::_parallel_evaluate<sferes::phen::Parameters<sferes::gen::EvoFloat<10, Params>, Rastrigin<Params>, Params> >; Partitioner = const tbb::auto_partitioner]’
/usr/include/tbb/partitioner.h:259:13:   required from ‘void tbb::interface6::internal::partition_type_base<Partition>::execute(StartType&, Range&) [with StartType = tbb::interface6::internal::start_for<tbb::blocked_range<long unsigned int>, sferes::eval::_parallel_evaluate<sferes::phen::Parameters<sferes::gen::EvoFloat<10, Params>, Rastrigin<Params>, Params> >, const tbb::auto_partitioner>; Range = tbb::blocked_range<long unsigned int>; Partition = tbb::interface6::internal::auto_partition_type]’
/usr/include/tbb/parallel_for.h:116:9:   required from ‘tbb::task\* tbb::interface6::internal::start_for<Range, Body, Partitioner>::execute() [with Range = tbb::blocked_range<long unsigned int>; Body = sferes::eval::_parallel_evaluate<sferes::phen::Parameters<sferes::gen::EvoFloat<10, Params>, Rastrigin<Params>, Params> >; Partitioner = const tbb::auto_partitioner]’
../modules/map_elites/test_map_elites.cpp:148:1:   required from here
../modules/map_elites/test_map_elites.cpp:124:68: error: in C++98 ‘data’ must be initialized by constructor, not by ‘{...}’
     std::vector<float> data = {ind.gen().data(0), ind.gen().data(1)};
                                                                    ^
../modules/map_elites/test_map_elites.cpp: In instantiation of ‘void Rastrigin<Params, Exact>::eval(Indiv&) [with Indiv = sferes::phen::Parameters<sferes::gen::EvoFloat<10, Params>, Rastrigin<Params>, Params>; Params = Params; Exact = stc::Itself]’:
../sferes/eval/parallel.hpp:63:11:   required from ‘void sferes::eval::_parallel_evaluate<Phen>::operator()(const range_t&) const [with Phen = sferes::phen::Parameters<sferes::gen::EvoFloat<10, Params>, Rastrigin<Params>, Params>; sferes::parallel::range_t = tbb::blocked_range<long unsigned int>]’
/usr/include/tbb/parallel_for.h:110:37:   required from ‘void tbb::interface6::internal::start_for<Range, Body, Partitioner>::run_body(Range&) [with Range = tbb::blocked_range<long unsigned int>; Body = sferes::eval::_parallel_evaluate<sferes::phen::Parameters<sferes::gen::EvoFloat<10, Params>, Rastrigin<Params>, Params> >; Partitioner = const tbb::auto_partitioner]’
/usr/include/tbb/partitioner.h:259:13:   required from ‘void tbb::interface6::internal::partition_type_base<Partition>::execute(StartType&, Range&) [with StartType = tbb::interface6::internal::start_for<tbb::blocked_range<long unsigned int>, sferes::eval::_parallel_evaluate<sferes::phen::Parameters<sferes::gen::EvoFloat<10, Params>, Rastrigin<Params>, Params> >, const tbb::auto_partitioner>; Range = tbb::blocked_range<long unsigned int>; Partition = tbb::interface6::internal::auto_partition_type]’
/usr/include/tbb/parallel_for.h:116:9:   required from ‘tbb::task\* tbb::interface6::internal::start_for<Range, Body, Partitioner>::execute() [with Range = tbb::blocked_range<long unsigned int>; Body = sferes::eval::_parallel_evaluate<sferes::phen::Parameters<sferes::gen::EvoFloat<10, Params>, Rastrigin<Params>, Params> >; Partitioner = const tbb::auto_partitioner]’
../modules/map_elites/test_map_elites.cpp:148:1:   required from here
../modules/map_elites/test_map_elites.cpp:124:68: error: in C++98 ‘data’ must be initialized by constructor, not by ‘{...}’
     std::vector<float> data = {ind.gen().data(0), ind.gen().data(1)};

**Comment by jbmouret** [comment]
Sorry, you should pull again and it should work. In addition, you could have switched to c++11 (./waf configure --cpp11=yes) if you compiler supports c++11.
